project:
  type: website
  output-dir: docs


website:
  title: "Amelia Henry"
  search: false
  sidebar:
    contents:
      - href: index.qmd
      - href: posts/aboutme.qmd
      - section: "Main Analyses"
        contents:
        - posts/hurdles.qmd
        - posts/sequenceandcluster.qmd
      - section: "Custom Functions"
        contents: 
        - posts/customflextable.qmd
      - section: "Notes"
        contents:
        - posts/scripts_and_workflow.qmd
        - posts/project_setup.qmd


## APPEARANCE 

format:
  html:
    code-fold: true
    code-summary: "Show/hide the code"
    code-overflow: wrap
    code-copy: true
    # code-tools:
    #   source: true
    #   toggle: false
    syntax-highlighting: 
      light: boilerplate.theme
      dark: arrow
    theme: 
      light: 
        - flatly
        - styles.scss
      dark: darkly 
    toc: false

knitr:
  opts_chunk:
    ft.htmlscroll: false
    message: false
    warning: false

