project:
  type: website
  output-dir: docs


website:
  title: "Amelia Henry"
  search: false
  bread-crumbs: true
  page-navigation: true
  navbar: 
    background: primary
    right:
      - text: "Home"
        href: index.qmd
      - href: aboutme.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Extras"
        href: extras.qmd
  sidebar: 
      # - title: "Projects"
      #   contents:
      #   - posts/projects/hurdles.qmd
      #   - posts/projects/sequenceandcluster.qmd
      - title: "Extras"
        contents:
          - section: "Custom Functions"
            contents: 
            - posts/extras/customflextable.qmd
          - section: "Notes"
            contents:
            - posts/extras/scripts_and_workflow.qmd
            - posts/extras/project_setup.qmd

## APPEARANCE 

format:
  html:
    code-fold: true
    code-summary: "Show/hide the code"
    code-overflow: wrap
    code-copy: true
    # code-tools:
    #   source: true
    #   toggle: false
    syntax-highlighting: 
      light: boilerplate.theme
      dark: arrow
    theme: 
      light: 
        - flatly
        - styles.scss
      dark: darkly 
    toc: true
    toc-location: left
    grid: 
      sidebar-width: 200px

knitr:
  opts_chunk:
    ft.htmlscroll: false
    message: false
    warning: false

