project:
  type: book
  output-dir: docs


book:
  title: "Amelia Henry"
  search: false
  chapters:
  ## HOME 
    - index.qmd
    - posts/aboutme.qmd
    - part: "Main Analyses"
      chapters:
      - posts/hurdles.qmd
      #- posts/sequenceandcluster.qmd
    # - part: "Other Analyses"
    #   chapters:
    #   - posts/multilevel.qmd
    - part: "Custom functions"
      chapters:
      - posts/customflextable.qmd
    - part: "Notes"
      chapters:
      - posts/scripts_and_workflow.qmd
      - posts/project_setup.qmd
    # - part: "Other Analyses"
    #   chapters:
    #   - posts/multilevel.qmd
    # - part: "Custom functions"
    #   chapters:
    #   - posts/customflextable.qmd
    # - part: "Notes"
    #   chapters:
    #   - posts/scripts_and_workflow.qmd
    #   - posts/project_setup.qmd

## APPEARANCE 


format:
  html:
    code-fold: show
    code-summary: "Show/hide the code"
    code-overflow: wrap
    code-copy: true
    # code-tools:
    #   source: true
    #   toggle: false
    syntax-highlighting: 
      light: atom-one
      dark: arrow
    theme: 
      light: flatly
      dark: darkly 
    toc: false

knitr:
  opts_chunk:
    ft.htmlscroll: false
    message: false
    warning: false

